# Generated by Django 3.2 on 2022-09-05 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('display_image', models.ImageField(default='default_butterfly.jpg', upload_to='display_images')),
                ('location', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('hidden', 'Hidden'), ('active', 'Active')], default='active', max_length=10)),
                ('animal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='members.animal')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
